Added Tooling and scripts for oscd
openscd/oscd-components pull request #25
Opened 2023-10-03 13:29 UTC by pascalwilbrink

2023-10-10 13:54 UTC, juancho0202 requested changes
One minor change and an open question 👍

2023-10-10 13:54 UTC, juancho0202 commented on tools/oscd/src/generators/component/files/src/__selector__.ts.template
> +    return {};
what is the purpose of this empty object being returned for new components?

2023-10-11 08:11 UTC, pascalwilbrink commented on tools/oscd/src/generators/component/files/src/__selector__.ts.template
> +    return {};
There is no purpose, it's only put in to remind devs that scopedElements are possible.

2023-10-11 08:18 UTC, pascalwilbrink commented on tools/oscd/src/generators/component/files/src/__selector__.ts.template
> +    return {};
I can remove it, but we have to keep in mind that this is possible. 
Scoped Registries are actively being worked on ATM.

2023-10-12 04:52 UTC, juancho0202 commented on tools/oscd/src/generators/component/files/src/__selector__.ts.template
> +    return {};
Oh ok, just wasn't familiar with the concept.
https://open-wc.org/docs/development/scoped-elements/ you mean this thing, right?
What are we planning on using that for?

2023-10-12 08:20 UTC, juancho0202 approved these changes

2023-10-12 08:20 UTC, merged